
# Install Required Python Libs

- apt: name=python-pycurl
       state=present


# Install & Configure Nginx

- apt_repository: repo='ppa:nginx/stable'
                  state=present

- apt: name=nginx-full
       state=present

- copy: src=nginx/nginx.conf
        dest=/etc/nginx/nginx.conf
  notify: reload nginx

#- copy: src=nginx/php.conf
#        dest=/etc/nginx/conf.d/php.conf
#  notify: reload nginx

# Install & Configure PHP

- apt_repository: repo='ppa:ondrej/php5'
                  state=present

- apt: name=php5-fpm
       state=present

- apt: name=php5-cli
       state=present


- file: path=/etc/php5/fpm/pool.d/www.conf
        state=absent
  notify: restart php-fpm


- name: Copy the php-fpm php.ini config file
  ini_file: dest=/etc/php5/fpm/conf.d/config.ini
            section=PHP
            option={{ item.option }}
            value={{ item.value }}
  with_items: php_config
  notify: restart php-fpm

- name: Copy the php-fpm php-fpm.conf configuration file
  ini_file: dest=/etc/php5/fpm/php-fpm.conf
            section={{ item.section }}
            option={{ item.option }}
            value={{ item.value }}
  with_items: fpm_config
  notify: restart php-fpm

- name: Copy the POOL configurations
  template: src=pool.conf
            dest=/etc/php5/fpm/pool.d/{{ item['pool']['name'] }}.conf
  with_items: fpm_pools
  when: fpm_pools|lower != 'none'
  notify: restart php-fpm

- name: Check php-fpm syntax of configuration files
  shell: php5-fpm -t
  register: result
  changed_when: "result.rc != 0"



# Install Git

-  apt: name=git
        state=present



- service: name=php5-fpm
           state=started
           enabled=yes


- service: name=nginx
           state=started
           enabled=yes
