

# Configure Timezone

- name: Change Timezone to UTC
  copy: src=timezone
        dest=/etc/timezone
  notify: update timezone


# Configure Hostname

- hostname: name={{ inventory_hostname_short }}

# Configure & Install NTP

- name: Install NTP
  apt: name=ntp
       state=present

- name: Configure NTP
  copy: src=ntp.conf
        dest=/etc/ntp.conf
  notify: restart ntp
